### ISSUE TITLE
Bloch various updates

### ISSUE THREAD

**Issue by AGaliciaMartinez** [qutip/qutip#1913]
### Describe the Issue!

As briefly described in #1910 there are some functions in `Bloch` class that are not fully tested. Besides, there are a few other changes that may benefit `Bloch`. I would like to list them here and provide more information on the change for discussion. 

The main changes I propose to do in the Bloch class are: 
- [x] clean-up of the code in `add_points` and `plot_points` methods (addressed in #1909).
- [x]  Clean import statements.
- [x] clean-up of the code in `add_vectors` and `plot_vectors` methods (#1917).
- [ ] clean-up of the code in `add_state` method. 
- [ ] make the plot functions (`plot_points, plot_vectors, ...`) private as they are meant to be used only in the render method (the do not even have a docstring). This _breaks backwards compatibility_ but I imagine it will be ok as I do not expect anyone using these methods.
- [x] Test `_repr_svg_` and `_repr_png_` (there seems to be a bug in `_repr_svg_` #1912).
- [ ] We have `render` and `make_sphere` methods that do _exactly_ the same (`make_sphere` calls `render`) I would vote to deprecate `make_sphere` for QuTiP 5.0.
- [ ] Make the interface consistent among the methods `add_state`, `add_vector`, `add_points`, `add_arc` and `add_line`. (This would address #1105 )
- [ ] Address #1106.
- [ ] Update documentation AND notebooks with changes.

These task are planned to be addressed each in a separate PR. I plan to finish these tasks myself but feel free to tackle any of these (or add a new one) if no PR is open and you mention it in this issue.

**Comment by hodgestar** [comment]
If you would like another item for the todo list, I'd really like to see the matplotlib aspects of the interface cleaned up. When we added the new lines and arcs features, we allowed passing arbitrary matplotlib plotting arguments as additional parameters. Perhaps we can do the same for the other functions and remove the old means of setting colours, etc?

**Comment by AGaliciaMartinez** [comment]
Yes, definitely! I would like to tackle that when with the item list "Make the interface consistent ..."

**Comment by Ericgig** [comment]
- [ ] Add control for the wireframe's linewidth #2396
